<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Career;

class UniversidadContinentalCareersSeeder extends Seeder
{
    public function run(): void
    {
        $careers = [
            // FACULTAD DE CIENCIAS DE LA EMPRESA
            [
                'name' => 'Administración y Finanzas',
                'code' => 'UC-CE-AF',
                'description' => 'Forma profesionales capaces de gestionar recursos financieros y administrativos de organizaciones, con visión estratégica y habilidades para la toma de decisiones en entornos empresariales.',
                'category' => 'Negocios y Administración',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Emprendedor',
                'riasec_scores' => json_encode(['R' => 2, 'I' => 3, 'A' => 1, 'S' => 3, 'E' => 5, 'C' => 5]),
                'required_skills' => json_encode(['Análisis financiero', 'Liderazgo', 'Toma de decisiones', 'Gestión de recursos']),
                'related_subjects' => json_encode(['Matemáticas', 'Economía', 'Comunicación']),
                'average_salary' => 3500.00,
                'duration_years' => 5,
                'job_opportunities' => 'Gerente financiero, Analista de inversiones, Controller, Auditor financiero, Consultor empresarial'
            ],
            [
                'name' => 'Administración y Gestión del Talento Humano',
                'code' => 'UC-CE-AGTH',
                'description' => 'Prepara especialistas en la gestión integral del capital humano, desarrollo organizacional, clima laboral y estrategias de retención de talento.',
                'category' => 'Recursos Humanos',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Social',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 2, 'A' => 2, 'S' => 5, 'E' => 4, 'C' => 3]),
                'required_skills' => json_encode(['Comunicación interpersonal', 'Empatía', 'Liderazgo', 'Resolución de conflictos']),
                'related_subjects' => json_encode(['Psicología', 'Comunicación', 'Desarrollo Personal']),
                'average_salary' => 3200.00,
                'duration_years' => 5,
                'job_opportunities' => 'Gerente de RRHH, Especialista en selección, Consultor organizacional, Analista de clima laboral'
            ],
            [
                'name' => 'Administración y Marketing',
                'code' => 'UC-CE-AM',
                'description' => 'Forma profesionales en estrategias de marketing digital, investigación de mercados, branding y gestión comercial para impulsar el crecimiento empresarial.',
                'category' => 'Marketing y Publicidad',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Emprendedor',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 2, 'A' => 4, 'S' => 4, 'E' => 5, 'C' => 2]),
                'required_skills' => json_encode(['Creatividad', 'Comunicación', 'Análisis de mercado', 'Marketing digital']),
                'related_subjects' => json_encode(['Comunicación', 'Matemáticas', 'Arte']),
                'average_salary' => 3300.00,
                'duration_years' => 5,
                'job_opportunities' => 'Gerente de marketing, Especialista en marketing digital, Brand manager, Analista de mercados'
            ],
            [
                'name' => 'Administración y Negocios Digitales',
                'code' => 'UC-CE-AND',
                'description' => 'Especializa en la gestión de negocios en entornos digitales, e-commerce, transformación digital y emprendimiento tecnológico.',
                'category' => 'Negocios Digitales',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Emprendedor',
                'riasec_scores' => json_encode(['R' => 2, 'I' => 4, 'A' => 3, 'S' => 2, 'E' => 5, 'C' => 3]),
                'required_skills' => json_encode(['Tecnología digital', 'Innovación', 'E-commerce', 'Análisis de datos']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Comunicación']),
                'average_salary' => 3800.00,
                'duration_years' => 5,
                'job_opportunities' => 'Gerente de e-commerce, Consultor digital, Emprendedor digital, Analista de negocios digitales'
            ],
            [
                'name' => 'Administración y Negocios Internacionales',
                'code' => 'UC-CE-ANI',
                'description' => 'Capacita en comercio exterior, logística internacional, negociación intercultural y gestión de operaciones globales.',
                'category' => 'Comercio Internacional',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Emprendedor',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 3, 'A' => 2, 'S' => 3, 'E' => 5, 'C' => 4]),
                'required_skills' => json_encode(['Idiomas', 'Negociación', 'Comercio exterior', 'Visión global']),
                'related_subjects' => json_encode(['Inglés', 'Ciencias Sociales', 'Matemáticas']),
                'average_salary' => 3600.00,
                'duration_years' => 5,
                'job_opportunities' => 'Gerente de comercio exterior, Analista de importaciones, Consultor internacional, Agente aduanero'
            ],
            [
                'name' => 'Contabilidad y Finanzas',
                'code' => 'UC-CE-CF',
                'description' => 'Forma contadores públicos especializados en auditoría, tributación, finanzas corporativas y gestión contable empresarial.',
                'category' => 'Contabilidad',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Convencional',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 3, 'A' => 1, 'S' => 2, 'E' => 3, 'C' => 5]),
                'required_skills' => json_encode(['Análisis numérico', 'Precisión', 'Normativa tributaria', 'Auditoría']),
                'related_subjects' => json_encode(['Matemáticas', 'Economía']),
                'average_salary' => 3400.00,
                'duration_years' => 5,
                'job_opportunities' => 'Contador público, Auditor, Analista financiero, Asesor tributario, Controller'
            ],
            [
                'name' => 'Economía',
                'code' => 'UC-CE-ECO',
                'description' => 'Prepara economistas con capacidad de análisis macroeconómico, políticas públicas, investigación económica y consultoría.',
                'category' => 'Economía',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 5, 'A' => 1, 'S' => 2, 'E' => 3, 'C' => 4]),
                'required_skills' => json_encode(['Análisis económico', 'Estadística', 'Investigación', 'Modelamiento']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencias Sociales']),
                'average_salary' => 3500.00,
                'duration_years' => 5,
                'job_opportunities' => 'Economista, Analista económico, Consultor, Investigador, Funcionario público'
            ],
            [
                'name' => 'Administración',
                'code' => 'UC-CE-ADM',
                'description' => 'Carrera integral que forma administradores con visión estratégica, liderazgo y capacidad de gestión empresarial en diversos sectores.',
                'category' => 'Administración General',
                'faculty' => 'Facultad de Ciencias de la Empresa',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Emprendedor',
                'riasec_scores' => json_encode(['R' => 2, 'I' => 3, 'A' => 2, 'S' => 3, 'E' => 5, 'C' => 3]),
                'required_skills' => json_encode(['Liderazgo', 'Planificación', 'Gestión', 'Toma de decisiones']),
                'related_subjects' => json_encode(['Matemáticas', 'Comunicación', 'Ciencias Sociales']),
                'average_salary' => 3300.00,
                'duration_years' => 5,
                'job_opportunities' => 'Gerente general, Administrador, Consultor empresarial, Emprendedor'
            ],

            // FACULTAD DE INGENIERÍA
            [
                'name' => 'Arquitectura',
                'code' => 'UC-ING-ARQ',
                'description' => 'Forma arquitectos con capacidad de diseño espacial, planificación urbana, construcción sostenible y gestión de proyectos arquitectónicos.',
                'category' => 'Arquitectura y Diseño',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Artístico',
                'riasec_scores' => json_encode(['R' => 4, 'I' => 3, 'A' => 5, 'S' => 2, 'E' => 3, 'C' => 2]),
                'required_skills' => json_encode(['Diseño', 'Creatividad', 'Dibujo técnico', 'Visión espacial']),
                'related_subjects' => json_encode(['Arte', 'Matemáticas', 'Ciencia y Tecnología']),
                'average_salary' => 3500.00,
                'duration_years' => 5,
                'job_opportunities' => 'Arquitecto, Diseñador urbano, Gestor de proyectos, Consultor en construcción'
            ],
            [
                'name' => 'Ingeniería Ambiental',
                'code' => 'UC-ING-AMB',
                'description' => 'Especializa en gestión ambiental, tratamiento de residuos, evaluación de impacto ambiental y desarrollo sostenible.',
                'category' => 'Ingeniería Ambiental',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 4, 'I' => 5, 'A' => 2, 'S' => 3, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Análisis ambiental', 'Química', 'Sostenibilidad', 'Investigación']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Matemáticas', 'Ciencias Sociales']),
                'average_salary' => 3200.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero ambiental, Consultor ambiental, Auditor ambiental, Gestor de proyectos sostenibles'
            ],
            [
                'name' => 'Ingeniería Civil',
                'code' => 'UC-ING-CIV',
                'description' => 'Forma ingenieros en diseño, construcción y supervisión de obras civiles, infraestructura vial, hidráulica y estructuras.',
                'category' => 'Ingeniería Civil',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Realista',
                'riasec_scores' => json_encode(['R' => 5, 'I' => 4, 'A' => 2, 'S' => 2, 'E' => 3, 'C' => 3]),
                'required_skills' => json_encode(['Cálculo estructural', 'Diseño', 'Gestión de obras', 'Topografía']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Educación para el Trabajo']),
                'average_salary' => 3800.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero civil, Residente de obra, Proyectista, Supervisor de construcción'
            ],
            [
                'name' => 'Ingeniería de Minas',
                'code' => 'UC-ING-MIN',
                'description' => 'Especializa en explotación minera, procesamiento de minerales, seguridad minera y gestión de operaciones mineras.',
                'category' => 'Ingeniería de Minas',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Realista',
                'riasec_scores' => json_encode(['R' => 5, 'I' => 4, 'A' => 1, 'S' => 2, 'E' => 3, 'C' => 3]),
                'required_skills' => json_encode(['Geología', 'Operaciones mineras', 'Seguridad', 'Gestión de recursos']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Educación Física']),
                'average_salary' => 5000.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero de minas, Supervisor de operaciones, Consultor minero, Gestor de seguridad'
            ],
            [
                'name' => 'Ingeniería de Sistemas e Informática',
                'code' => 'UC-ING-SIS',
                'description' => 'Forma ingenieros en desarrollo de software, gestión de tecnologías de información, ciberseguridad y transformación digital.',
                'category' => 'Ingeniería de Sistemas',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 3, 'I' => 5, 'A' => 2, 'S' => 2, 'E' => 3, 'C' => 4]),
                'required_skills' => json_encode(['Programación', 'Lógica', 'Análisis de sistemas', 'Resolución de problemas']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Inglés']),
                'average_salary' => 4200.00,
                'duration_years' => 5,
                'job_opportunities' => 'Desarrollador de software, Analista de sistemas, Arquitecto de software, Consultor TI'
            ],
            [
                'name' => 'Ingeniería Eléctrica',
                'code' => 'UC-ING-ELE',
                'description' => 'Especializa en sistemas eléctricos de potencia, automatización, energías renovables y gestión energética.',
                'category' => 'Ingeniería Eléctrica',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Realista',
                'riasec_scores' => json_encode(['R' => 5, 'I' => 4, 'A' => 1, 'S' => 1, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Electricidad', 'Electrónica', 'Automatización', 'Análisis técnico']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Educación para el Trabajo']),
                'average_salary' => 3900.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero eléctrico, Especialista en energía, Supervisor de mantenimiento, Consultor energético'
            ],
            [
                'name' => 'Ingeniería Empresarial',
                'code' => 'UC-ING-EMP',
                'description' => 'Combina ingeniería con gestión empresarial para optimizar procesos, mejorar productividad y liderar proyectos de innovación.',
                'category' => 'Ingeniería Empresarial',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Emprendedor',
                'riasec_scores' => json_encode(['R' => 3, 'I' => 4, 'A' => 2, 'S' => 3, 'E' => 5, 'C' => 3]),
                'required_skills' => json_encode(['Gestión de proyectos', 'Optimización', 'Liderazgo', 'Innovación']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Comunicación']),
                'average_salary' => 3700.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero empresarial, Consultor, Gerente de operaciones, Analista de procesos'
            ],
            [
                'name' => 'Ingeniería Industrial',
                'code' => 'UC-ING-IND',
                'description' => 'Forma ingenieros en optimización de procesos productivos, gestión de calidad, logística y mejora continua.',
                'category' => 'Ingeniería Industrial',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Realista',
                'riasec_scores' => json_encode(['R' => 4, 'I' => 4, 'A' => 1, 'S' => 2, 'E' => 4, 'C' => 4]),
                'required_skills' => json_encode(['Optimización', 'Gestión de producción', 'Calidad', 'Logística']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Educación para el Trabajo']),
                'average_salary' => 3800.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero industrial, Jefe de producción, Analista de procesos, Consultor de calidad'
            ],
            [
                'name' => 'Ingeniería Mecánica',
                'code' => 'UC-ING-MEC',
                'description' => 'Especializa en diseño mecánico, manufactura, mantenimiento industrial y gestión de sistemas mecánicos.',
                'category' => 'Ingeniería Mecánica',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Realista',
                'riasec_scores' => json_encode(['R' => 5, 'I' => 4, 'A' => 2, 'S' => 1, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Diseño mecánico', 'Manufactura', 'Termodinámica', 'CAD/CAM']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Educación para el Trabajo']),
                'average_salary' => 3700.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero mecánico, Diseñador industrial, Jefe de mantenimiento, Consultor técnico'
            ],
            [
                'name' => 'Ingeniería Mecatrónica',
                'code' => 'UC-ING-MECA',
                'description' => 'Integra mecánica, electrónica y programación para desarrollar sistemas automatizados, robótica e industria 4.0.',
                'category' => 'Ingeniería Mecatrónica',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Realista',
                'riasec_scores' => json_encode(['R' => 5, 'I' => 5, 'A' => 2, 'S' => 1, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Robótica', 'Automatización', 'Programación', 'Electrónica']),
                'related_subjects' => json_encode(['Matemáticas', 'Ciencia y Tecnología', 'Educación para el Trabajo']),
                'average_salary' => 4000.00,
                'duration_years' => 5,
                'job_opportunities' => 'Ingeniero mecatrónico, Especialista en automatización, Desarrollador de robótica, Consultor en industria 4.0'
            ],
            [
                'name' => 'Arquitectura y Diseño de Interiores',
                'code' => 'UC-ING-ADI',
                'description' => 'Combina arquitectura con diseño de espacios interiores, mobiliario, ambientación y proyectos de interiorismo.',
                'category' => 'Diseño de Interiores',
                'faculty' => 'Facultad de Ingeniería',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Artístico',
                'riasec_scores' => json_encode(['R' => 3, 'I' => 2, 'A' => 5, 'S' => 2, 'E' => 3, 'C' => 2]),
                'required_skills' => json_encode(['Diseño', 'Creatividad', 'Estética', 'Dibujo técnico']),
                'related_subjects' => json_encode(['Arte', 'Matemáticas', 'Comunicación']),
                'average_salary' => 3300.00,
                'duration_years' => 5,
                'job_opportunities' => 'Diseñador de interiores, Arquitecto de interiores, Consultor de diseño, Gestor de proyectos'
            ],

            // FACULTAD DE HUMANIDADES
            [
                'name' => 'Ciencias de la Comunicación',
                'code' => 'UC-HUM-COM',
                'description' => 'Forma comunicadores integrales en periodismo, comunicación corporativa, producción audiovisual y gestión de medios digitales.',
                'category' => 'Comunicación',
                'faculty' => 'Facultad de Humanidades',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Artístico',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 3, 'A' => 5, 'S' => 4, 'E' => 4, 'C' => 2]),
                'required_skills' => json_encode(['Redacción', 'Comunicación', 'Creatividad', 'Producción audiovisual']),
                'related_subjects' => json_encode(['Comunicación', 'Arte', 'Ciencias Sociales']),
                'average_salary' => 2800.00,
                'duration_years' => 5,
                'job_opportunities' => 'Periodista, Comunicador corporativo, Productor audiovisual, Community manager, Relacionista público'
            ],
            [
                'name' => 'Psicología',
                'code' => 'UC-HUM-PSI',
                'description' => 'Prepara psicólogos en áreas clínica, organizacional, educativa y social para promover el bienestar mental y desarrollo humano.',
                'category' => 'Psicología',
                'faculty' => 'Facultad de Humanidades',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Social',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 4, 'A' => 2, 'S' => 5, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Empatía', 'Escucha activa', 'Análisis', 'Intervención psicológica']),
                'related_subjects' => json_encode(['Desarrollo Personal', 'Ciencias Sociales', 'Comunicación']),
                'average_salary' => 2900.00,
                'duration_years' => 5,
                'job_opportunities' => 'Psicólogo clínico, Psicólogo organizacional, Psicólogo educativo, Consultor, Terapeuta'
            ],

            // FACULTAD DE DERECHO
            [
                'name' => 'Derecho',
                'code' => 'UC-DER-DER',
                'description' => 'Forma abogados con sólida formación jurídica, capacidad de litigio, asesoría legal y defensa de derechos.',
                'category' => 'Derecho',
                'faculty' => 'Facultad de Derecho',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Convencional',
                'riasec_scores' => json_encode(['R' => 1, 'I' => 4, 'A' => 2, 'S' => 3, 'E' => 4, 'C' => 5]),
                'required_skills' => json_encode(['Argumentación', 'Análisis legal', 'Oratoria', 'Investigación jurídica']),
                'related_subjects' => json_encode(['Comunicación', 'Ciencias Sociales', 'Ciudadanía y Cívica']),
                'average_salary' => 3500.00,
                'duration_years' => 5,
                'job_opportunities' => 'Abogado litigante, Asesor legal, Fiscal, Juez, Notario, Consultor jurídico'
            ],

            // FACULTAD DE SALUD
            [
                'name' => 'Enfermería',
                'code' => 'UC-SAL-ENF',
                'description' => 'Forma enfermeros profesionales en cuidado integral de la salud, prevención, promoción y atención de pacientes.',
                'category' => 'Enfermería',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Social',
                'riasec_scores' => json_encode(['R' => 3, 'I' => 3, 'A' => 1, 'S' => 5, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Cuidado del paciente', 'Empatía', 'Trabajo en equipo', 'Procedimientos clínicos']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Desarrollo Personal', 'Educación Física']),
                'average_salary' => 2800.00,
                'duration_years' => 5,
                'job_opportunities' => 'Enfermero clínico, Enfermero especialista, Gestor de salud, Docente'
            ],
            [
                'name' => 'Farmacia y Bioquímica',
                'code' => 'UC-SAL-FAR',
                'description' => 'Especializa en farmacología, química farmacéutica, gestión farmacéutica y atención farmacéutica.',
                'category' => 'Farmacia',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 2, 'I' => 5, 'A' => 1, 'S' => 3, 'E' => 2, 'C' => 4]),
                'required_skills' => json_encode(['Química', 'Farmacología', 'Análisis', 'Atención al paciente']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Matemáticas', 'Comunicación']),
                'average_salary' => 3200.00,
                'duration_years' => 5,
                'job_opportunities' => 'Químico farmacéutico, Regente de farmacia, Analista de laboratorio, Consultor farmacéutico'
            ],
            [
                'name' => 'Medicina Humana',
                'code' => 'UC-SAL-MED',
                'description' => 'Forma médicos cirujanos con excelencia clínica, capacidad diagnóstica, tratamiento y prevención de enfermedades.',
                'category' => 'Medicina',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 3, 'I' => 5, 'A' => 1, 'S' => 5, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Diagnóstico', 'Conocimiento médico', 'Empatía', 'Toma de decisiones']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Matemáticas', 'Desarrollo Personal']),
                'average_salary' => 5500.00,
                'duration_years' => 7,
                'job_opportunities' => 'Médico general, Médico especialista, Cirujano, Investigador médico, Docente'
            ],
            [
                'name' => 'Odontología',
                'code' => 'UC-SAL-ODO',
                'description' => 'Especializa en salud bucal, diagnóstico, tratamiento y prevención de enfermedades dentales y maxilofaciales.',
                'category' => 'Odontología',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 4, 'I' => 4, 'A' => 2, 'S' => 4, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Destreza manual', 'Diagnóstico', 'Atención al paciente', 'Procedimientos dentales']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Educación para el Trabajo', 'Desarrollo Personal']),
                'average_salary' => 3800.00,
                'duration_years' => 6,
                'job_opportunities' => 'Odontólogo general, Odontólogo especialista, Cirujano maxilofacial, Docente'
            ],
            [
                'name' => 'Tecnología Médica – Especialidad en Terapia Física y Rehabilitación',
                'code' => 'UC-SAL-TFR',
                'description' => 'Forma tecnólogos médicos especializados en rehabilitación física, fisioterapia y recuperación funcional.',
                'category' => 'Tecnología Médica',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Social',
                'riasec_scores' => json_encode(['R' => 4, 'I' => 3, 'A' => 1, 'S' => 5, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Terapia física', 'Rehabilitación', 'Empatía', 'Conocimiento anatómico']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Educación Física', 'Desarrollo Personal']),
                'average_salary' => 2900.00,
                'duration_years' => 5,
                'job_opportunities' => 'Tecnólogo médico en terapia física, Fisioterapeuta, Rehabilitador, Especialista deportivo'
            ],
            [
                'name' => 'Tecnología Médica – Laboratorio Clínico y Anatomía Patológica',
                'code' => 'UC-SAL-LAB',
                'description' => 'Especializa en análisis clínicos, diagnóstico de laboratorio, histopatología y control de calidad analítico.',
                'category' => 'Tecnología Médica',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 3, 'I' => 5, 'A' => 1, 'S' => 2, 'E' => 2, 'C' => 4]),
                'required_skills' => json_encode(['Análisis de laboratorio', 'Precisión', 'Conocimiento técnico', 'Investigación']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Matemáticas', 'Educación para el Trabajo']),
                'average_salary' => 3000.00,
                'duration_years' => 5,
                'job_opportunities' => 'Tecnólogo médico de laboratorio, Analista clínico, Jefe de laboratorio, Investigador'
            ],
            [
                'name' => 'Tecnología Médica - Radiología',
                'code' => 'UC-SAL-RAD',
                'description' => 'Forma tecnólogos médicos en imagenología, radiodiagnóstico, radioterapia y medicina nuclear.',
                'category' => 'Tecnología Médica',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Investigador',
                'riasec_scores' => json_encode(['R' => 4, 'I' => 4, 'A' => 1, 'S' => 3, 'E' => 2, 'C' => 4]),
                'required_skills' => json_encode(['Imagenología', 'Tecnología médica', 'Precisión', 'Atención al paciente']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Matemáticas', 'Educación para el Trabajo']),
                'average_salary' => 3100.00,
                'duration_years' => 5,
                'job_opportunities' => 'Tecnólogo médico en radiología, Especialista en imagenología, Radiólogo, Técnico en radioterapia'
            ],
            [
                'name' => 'Nutrición y Dietética',
                'code' => 'UC-SAL-NUT',
                'description' => 'Especializa en nutrición clínica, dietoterapia, salud pública nutricional y gestión de servicios alimentarios.',
                'category' => 'Nutrición',
                'faculty' => 'Facultad de Salud',
                'university' => 'Universidad Continental',
                'campus' => 'Huancayo',
                'riasec_profile' => 'Social',
                'riasec_scores' => json_encode(['R' => 2, 'I' => 4, 'A' => 1, 'S' => 5, 'E' => 2, 'C' => 3]),
                'required_skills' => json_encode(['Nutrición', 'Dietética', 'Consejería', 'Evaluación nutricional']),
                'related_subjects' => json_encode(['Ciencia y Tecnología', 'Matemáticas', 'Desarrollo Personal']),
                'average_salary' => 2800.00,
                'duration_years' => 5,
                'job_opportunities' => 'Nutricionista clínico, Nutricionista deportivo, Consultor nutricional, Gestor de servicios alimentarios'
            ],
        ];

        foreach ($careers as $career) {
            Career::create($career);
        }
    }
}
